### ISSUE TITLE
Armature animations aren't applied to mesh

### ISSUE THREAD

**Issue by sacrish** [EdyJ/blender-to-unity-fbx-exporter#10]
When exporting a skinned mesh, only the animations of the armature itself are exported, but the weight painting and vertex groups on the mesh are lost.

**Comment by EdyJ** [comment]
Are those exported correctly using the standard FBX Exporter?

**Comment by sacrish** [comment]
Yes the objects can be properly exported with the standard exporter, with default settings. 

Here is a test file. It has a cylinder mesh and an simple armature. No matter which options I enable with the Unity FBX Exporter, I can't get the weights to be exported. 

[FBX_export_test.zip](https://github.com/EdyJ/blender-to-unity-fbx-exporter/files/5223941/FBX_export_test.zip)

**Comment by EdyJ** [comment]
Thanks, will take a look at it.

**Comment by EdyJ** [comment]
The problem is that modifiers are applied before fixing the rotations, so applying the Armature modifier to the cylinder actually freezes it. The default FBX exporter lets this modifier pass through even with the Apply Modifiers enabled. I'll modify the Unity FBX exporter not to apply the Armature modifier.

**Comment by EdyJ** [comment]
Please test this version and let me know if it works:
https://github.com/EdyJ/blender-to-unity-fbx-exporter/blob/dev/fix-armature/blender-to-unity-fbx-exporter.py

**Comment by sacrish** [comment]
I've tested the file and armatures are now exported correctly. Thanks!
