### ISSUE TITLE
Wheel location transform and full FBX rotated while rotation value is 0

### ISSUE THREAD

**Issue by CheapWebdesign** [EdyJ/blender-to-unity-fbx-exporter#18]
Trying to use the cars from the Transportation add-on for Blender in Unity with the Edy's Vehicle Physics. Though, when i use this Blender-to-Unity-FBX-exporter is get the following strange behaviour, on any car i try to export to Unity. 

- The wheels location get's transformed outside the vehicles.
- The full FBX model is rotated itself, though the rotation value is 0. 

The versions of Blender and Unity I'm using: 

- Blender 2.83
- Unity 2020.3.0f1

See screenshots for an instant understanding of the problem. 

Here you see the vehicle after importing it into Unity: 
![merc1](https://user-images.githubusercontent.com/20015201/115966322-ef78a900-a524-11eb-83c1-b2341d510e15.JPG)

Here is the vehicle from Transportation add-on in Blender, all fresh no edits made:
![merc2](https://user-images.githubusercontent.com/20015201/115966427-6746d380-a525-11eb-98ad-2d337d124c84.JPG)

I've tried to follow the instructions provided in the Readme of this git, though, i can't get it working. With the rotation I noticed the Wheelcolliders from the Vehicle Physics add-on are not working on the road..

**Comment by EdyJ** [comment]
Can you provide some .blend file that can be used to reproduce the issue?

**Comment by CheapWebdesign** [comment]
Thank you for the quick response, as Github doesn't support .blend I have put it in a zip file.
Hopefully you're able to find the problem/solution, as I'm more than willing to use this in your vehicle physics pack for Unity :) 

[bmw.zip](https://github.com/EdyJ/blender-to-unity-fbx-exporter/files/6372309/bmw.zip)

**Comment by EdyJ** [comment]
Unfortunately I couldn't do anything with that .blend file. It shows collections only, no hierarchy nor meshes. I can't even switch between Object and Edit mode! (the menu shows Object mode only). Am I missing something?

This is how the hierarchy looks when I open that file:
![image](https://user-images.githubusercontent.com/6773528/116075292-10f7a300-a693-11eb-81f5-21b9cc725bf9.png)

How could I see or "expand" the actual Object hierarchy?

**Comment by CheapWebdesign** [comment]
That's strange.. Might be because of the way the Transportation add-on works? I have to click on 'Make editable for animation' before I can see the hierarchy. Do you have any experience on this? 

This is how i see the file I shared.. 
![bmw1](https://user-images.githubusercontent.com/20015201/116088640-f5dc6180-a699-11eb-8e00-4ef61ac74650.JPG)

**Comment by EdyJ** [comment]
Probably. I can only see the objects by using the command "Make Instances Real", but then the hierarchy is flat and disconnected. Exporting the file now mostly works and all objects except one are in their correct pose. But no armature nor animation are exported, possibly because of the "Make Instances Real" command. 
![image](https://user-images.githubusercontent.com/6773528/116142746-92beef00-a6da-11eb-8823-7aca566b0f43.png)

Still, the resulting objects are not suitable for realtime animation in Unity. There's no proper hierarchy, the origins of the moving parts (wheels, suspension) are not configured, and the objects include unnecessary rotations in the Blender file. The same happens when using the stock FBX exporter. Those rotations are properly exported to Unity, but they make no sense in vehicles.

It seems that the Transportation add-on is specifically designed to be used within Blender for animations, cut scenes, CG pictures, showcases, etc but not to export the vehicles for realtime simulation. Using these vehicles in Unity (or any other engine) would require these steps in Blender:

1. Convert the vehicle to standard Blender objects (i.e. with "Make Instances Real").
2. Remove unwanted rotations from the objects.
3. Recreate the object hierachy.
4. Apply correct origins to the wheels and any other moving parts.
5. Remove animation, armature, etc (now they're disconnected from the objects).
6. Export the file to Unity FBX.

Unfortunately there's nothing else I could do here, as that's the way the Transportation tool works.

**Comment by CheapWebdesign** [comment]
Thanks a lot for thinking along, muy appreciated! When I get some more time, I will try the method you described. For now I'll stick to exporting as *.obj . That is working fine in Unity. Your Vehicle Physics for Unity runs like a charm with these cars! 

I think this 'issue' can be closed, as it's has little to do with your Blender-to-Unity-FBX-Exporter.

**Comment by EdyJ** [comment]
Cool, good to know!
